/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amvrutinario;

import amvrutinario.dao.ProyectoDao;
import amvrutinario.dto.Proyecto;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author Daniel
 */
public class Bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form Bienvenida
     */
    public Bienvenida() {
        initComponents();
        loadProyects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagen = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProyectos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(720, 447));
        setLayout(null);

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amvrutinario/resources/ico.png"))); // NOI18N
        add(Imagen);
        Imagen.setBounds(10, 11, 384, 384);

        subtitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        subtitulo.setText("Abrir un proyecto previamente creado");
        add(subtitulo);
        subtitulo.setBounds(420, 190, 243, 18);

        titulo.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 204, 51));
        titulo.setText("AMV Rutinario");
        add(titulo);
        titulo.setBounds(433, 73, 301, 57);

        tablaProyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CTA", "PR Inicio", "PR FIN", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProyectos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProyectos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tablaProyectosMouseMoved(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProyectos);

        add(jScrollPane2);
        jScrollPane2.setBounds(420, 222, 330, 180);

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(593, 410, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Objects.nonNull(tablaProyectos.getSelectedRow())) {
            Object selectedRow = tablaProyectos.getValueAt(tablaProyectos.getSelectedRow(), 3);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaProyectosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProyectosMouseMoved

    }//GEN-LAST:event_tablaProyectosMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JTable tablaProyectos;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    public void loadProyects() {
        try {
            DefaultTableModel model = (DefaultTableModel) tablaProyectos.getModel();
            ProyectoDao dao = new ProyectoDao();
            List<Proyecto> proyectos = dao.getAll();
            proyectos.forEach(pr -> {
                model.addRow(new String[]{pr.getCta(), pr.getPrInicial(), pr.getPrFinal(), pr.getId().toString()});
            });
            tablaProyectos.getColumnModel().getColumn(3).setMinWidth(0);
            tablaProyectos.getColumnModel().getColumn(3).setMaxWidth(0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
