/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package amvrutinario;

import amvrutinario.dto.Indicador;
import amvrutinario.dto.Proyecto;
import amvrutinario.dto.ProyectoDto;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author Daniel
 */
public class CrearProyecto extends javax.swing.JPanel {

    private List<Indicador> indicadors;

    /**
     * Creates new form ProyectoNuevo
     */
    public CrearProyecto() {
        initComponents();
        indicadors = new ArrayList<>();
    }

    CrearProyecto(int id) {
        initComponents();
        indicadors = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tabPanel = new javax.swing.JTabbedPane();
        jPanelGeneralidades = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIngenieroResidente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIngenieroAuxiliar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSectorAdministrativo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionOficina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAMV = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCTA = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtTipoTerreno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSector = new javax.swing.JTextField();
        btnGeneralidades = new javax.swing.JButton();
        txtCelulares = new javax.swing.JFormattedTextField();
        txtPRFinalGeneralidades = new javax.swing.JFormattedTextField();
        txtPRInicialGeneralidades1 = new javax.swing.JFormattedTextField();
        jPanelBacheo = new javax.swing.JPanel();
        tipoIndicadorBacheo = new javax.swing.JComboBox<>();
        tipoInformeBacheo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listBacheoClima = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtBacheoHorasUtilizadas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBacheoEquipo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtBacheoCantidadEjecutada = new javax.swing.JTextField();
        btnBacheoContinuar = new javax.swing.JButton();
        btnBacheoGuardar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtBacheoRendimiento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBacheoObservacion = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        txtBacheoHoras = new javax.swing.JFormattedTextField();
        txtBacheoPRFin = new javax.swing.JFormattedTextField();
        txtBacheoPRInicio = new javax.swing.JFormattedTextField();
        txtBacheoObreros = new javax.swing.JFormattedTextField();
        jLabel38 = new javax.swing.JLabel();
        num_bacheos = new javax.swing.JLabel();
        jPanelParcheo = new javax.swing.JPanel();
        tipoIndicadorParcheo = new javax.swing.JComboBox<>();
        tipoInformeParcheo = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listParcheoClima = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtParcheoTotalHoras = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtEquipoParcheo = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtCantidadEjecutadaParcheo = new javax.swing.JTextField();
        btnParcheoContinuar = new javax.swing.JButton();
        btnParcheoGuardar = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtRendimientoParcheo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtParcheoObservacion = new javax.swing.JTextArea();
        jLabel37 = new javax.swing.JLabel();
        txtParcheoHoras = new javax.swing.JFormattedTextField();
        txtParcheoPRFin = new javax.swing.JFormattedTextField();
        txtParcheoPRInicio = new javax.swing.JFormattedTextField();
        txtParcheoObreros = new javax.swing.JFormattedTextField();
        jPanelLimpieza = new javax.swing.JPanel();
        tipoLimpieza = new javax.swing.JComboBox<>();
        tipoInformeLimpieza = new javax.swing.JComboBox<>();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        listClimaLimpieza = new javax.swing.JList<>();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        txtHorasUtilizadasLimpieza = new javax.swing.JTextField();
        jLabel100 = new javax.swing.JLabel();
        txtEquipoLimpieza = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        txtCantidadEjecutadaLimpieza = new javax.swing.JTextField();
        btnContinuarLimpieza = new javax.swing.JButton();
        btnGuardarLimpieza = new javax.swing.JButton();
        jLabel102 = new javax.swing.JLabel();
        txtRendimientoLimpieza = new javax.swing.JTextField();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtObservacionLimpieza = new javax.swing.JTextArea();
        jLabel103 = new javax.swing.JLabel();
        txtHorasLimpieza = new javax.swing.JFormattedTextField();
        txtPRFinLimpieza = new javax.swing.JFormattedTextField();
        txtPRInicioLimpieza = new javax.swing.JFormattedTextField();
        txtObrerosLimpieza = new javax.swing.JFormattedTextField();
        jPanelMantenimiento = new javax.swing.JPanel();
        tipoMantenimiento = new javax.swing.JComboBox<>();
        tipoInformeMatenimiento = new javax.swing.JComboBox<>();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        listClimaMantenimiento = new javax.swing.JList<>();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        txtHorasUtilizadasMantenimiento = new javax.swing.JTextField();
        jLabel111 = new javax.swing.JLabel();
        txtEquipoManenimiento = new javax.swing.JTextField();
        jLabel112 = new javax.swing.JLabel();
        txtCantidadEjecutadaMantenimiento = new javax.swing.JTextField();
        btnContinuarMantenimiento = new javax.swing.JButton();
        btnGuardarMantenimiento = new javax.swing.JButton();
        jLabel113 = new javax.swing.JLabel();
        txtRendimientoMantenimiento = new javax.swing.JTextField();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtObservacionMantenimiento = new javax.swing.JTextArea();
        jLabel114 = new javax.swing.JLabel();
        txtHorasMantenimiento = new javax.swing.JFormattedTextField();
        txtPRFinMantenimiento = new javax.swing.JFormattedTextField();
        txtPRInicioMantenimiento = new javax.swing.JFormattedTextField();
        txtObrerosMantenimiento = new javax.swing.JFormattedTextField();
        jPanelObrasComplementarias = new javax.swing.JPanel();
        tipoObraComplementaria = new javax.swing.JComboBox<>();
        tipoInformeObraComplementaria = new javax.swing.JComboBox<>();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        listClimaObraComplementaria = new javax.swing.JList<>();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        txtHorasUtilizadasObraComplementaria = new javax.swing.JTextField();
        jLabel122 = new javax.swing.JLabel();
        txtEquipoObraComplementaria = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        txtCantidadEjecutadaObraComplementaria = new javax.swing.JTextField();
        btnContinuarObraComplementaria = new javax.swing.JButton();
        btnGuardarObraComplementaria = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        txtRendimientoObraComplementaria = new javax.swing.JTextField();
        jScrollPane20 = new javax.swing.JScrollPane();
        txtObservacionObraComplementaria = new javax.swing.JTextArea();
        jLabel125 = new javax.swing.JLabel();
        txtHorasObraComplementaria = new javax.swing.JFormattedTextField();
        txtPRFinObraComplementaria = new javax.swing.JFormattedTextField();
        txtPRInicioObraComplementaria = new javax.swing.JFormattedTextField();
        txtObrerosObraComplementaria = new javax.swing.JFormattedTextField();
        jPanelPinturas = new javax.swing.JPanel();
        tipoPintura = new javax.swing.JComboBox<>();
        tipoInformePintura = new javax.swing.JComboBox<>();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        listClimaPintura = new javax.swing.JList<>();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        txtHorasUtilizadasPintura = new javax.swing.JTextField();
        jLabel133 = new javax.swing.JLabel();
        txtEquipoPintura = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        txtCantidadEjecutadaPintura = new javax.swing.JTextField();
        btnGuardarPintura = new javax.swing.JButton();
        jLabel135 = new javax.swing.JLabel();
        txtRendimientoPintura = new javax.swing.JTextField();
        jScrollPane22 = new javax.swing.JScrollPane();
        txtObservacionPintura = new javax.swing.JTextArea();
        jLabel136 = new javax.swing.JLabel();
        txtHorasPintura = new javax.swing.JFormattedTextField();
        txtPRFinPintura = new javax.swing.JFormattedTextField();
        txtPRInicioPintura = new javax.swing.JFormattedTextField();
        txtObrerosPintura = new javax.swing.JFormattedTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable1);

        setLayout(new java.awt.GridLayout(1, 0));

        tabPanel.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanelGeneralidades.setLayout(null);

        jLabel1.setText("Nombre del Ingeniero Residente");
        jPanelGeneralidades.add(jLabel1);
        jLabel1.setBounds(10, 10, 250, 20);

        txtIngenieroResidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIngenieroResidenteActionPerformed(evt);
            }
        });
        jPanelGeneralidades.add(txtIngenieroResidente);
        txtIngenieroResidente.setBounds(260, 10, 500, 25);

        jLabel2.setText("Nombre del Ingeniero Auxiliar");
        jPanelGeneralidades.add(jLabel2);
        jLabel2.setBounds(10, 40, 250, 20);
        jPanelGeneralidades.add(txtIngenieroAuxiliar);
        txtIngenieroAuxiliar.setBounds(260, 40, 500, 25);

        jLabel3.setText("Sector Administrativo");
        jPanelGeneralidades.add(jLabel3);
        jLabel3.setBounds(10, 70, 250, 20);
        jPanelGeneralidades.add(txtSectorAdministrativo);
        txtSectorAdministrativo.setBounds(260, 70, 500, 25);

        jLabel4.setText("Direccion Oficina");
        jPanelGeneralidades.add(jLabel4);
        jLabel4.setBounds(10, 100, 250, 20);
        jPanelGeneralidades.add(txtDireccionOficina);
        txtDireccionOficina.setBounds(260, 100, 500, 25);

        jLabel5.setText("Telefonos");
        jPanelGeneralidades.add(jLabel5);
        jLabel5.setBounds(10, 130, 250, 20);
        jPanelGeneralidades.add(txtTelefono);
        txtTelefono.setBounds(260, 130, 96, 25);

        jLabel7.setText("Celular");
        jPanelGeneralidades.add(jLabel7);
        jLabel7.setBounds(370, 130, 90, 20);

        jLabel8.setText("FAX");
        jPanelGeneralidades.add(jLabel8);
        jLabel8.setBounds(620, 130, 40, 20);
        jPanelGeneralidades.add(txtFax);
        txtFax.setBounds(660, 130, 100, 25);

        jLabel9.setText("Correo Electrónico");
        jPanelGeneralidades.add(jLabel9);
        jLabel9.setBounds(10, 160, 250, 20);
        jPanelGeneralidades.add(txtCorreo);
        txtCorreo.setBounds(260, 160, 500, 25);

        jLabel10.setText("Administrador Vial");
        jPanelGeneralidades.add(jLabel10);
        jLabel10.setBounds(10, 190, 250, 20);
        jPanelGeneralidades.add(txtAMV);
        txtAMV.setBounds(260, 190, 500, 25);

        jLabel20.setText("Nombre de la cooperativa");
        jPanelGeneralidades.add(jLabel20);
        jLabel20.setBounds(10, 220, 250, 20);
        jPanelGeneralidades.add(txtCTA);
        txtCTA.setBounds(260, 220, 220, 25);

        jLabel21.setText("Tipo Terreno");
        jPanelGeneralidades.add(jLabel21);
        jLabel21.setBounds(510, 220, 100, 20);
        jPanelGeneralidades.add(txtTipoTerreno);
        txtTipoTerreno.setBounds(620, 220, 140, 25);

        jLabel22.setText("Logitud de Asignada");
        jPanelGeneralidades.add(jLabel22);
        jLabel22.setBounds(10, 250, 250, 20);
        jPanelGeneralidades.add(txtLongitud);
        txtLongitud.setBounds(260, 250, 100, 25);

        jLabel23.setText("PR Inicial");
        jPanelGeneralidades.add(jLabel23);
        jLabel23.setBounds(380, 250, 80, 20);

        jLabel24.setText("PR Final");
        jPanelGeneralidades.add(jLabel24);
        jLabel24.setBounds(380, 280, 80, 20);

        jLabel6.setText("Sector");
        jPanelGeneralidades.add(jLabel6);
        jLabel6.setBounds(10, 280, 250, 20);

        txtSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSectorActionPerformed(evt);
            }
        });
        jPanelGeneralidades.add(txtSector);
        txtSector.setBounds(260, 280, 100, 25);

        btnGeneralidades.setText("Continuar");
        btnGeneralidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralidadesActionPerformed(evt);
            }
        });
        jPanelGeneralidades.add(btnGeneralidades);
        btnGeneralidades.setBounds(610, 310, 150, 25);

        try {
            txtCelulares.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelGeneralidades.add(txtCelulares);
        txtCelulares.setBounds(430, 130, 180, 25);

        try {
            txtPRFinalGeneralidades.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelGeneralidades.add(txtPRFinalGeneralidades);
        txtPRFinalGeneralidades.setBounds(470, 280, 100, 25);

        try {
            txtPRInicialGeneralidades1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelGeneralidades.add(txtPRInicialGeneralidades1);
        txtPRInicialGeneralidades1.setBounds(470, 250, 100, 25);

        tabPanel.addTab("Generalidades", jPanelGeneralidades);

        jPanelBacheo.setLayout(null);

        tipoIndicadorBacheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de bacheo", "Carreteras Pavimentadas", "Carreteras Destapadas" }));
        tipoIndicadorBacheo.setToolTipText("Seleccione un tipo de bacheo");
        jPanelBacheo.add(tipoIndicadorBacheo);
        tipoIndicadorBacheo.setBounds(10, 10, 180, 25);

        tipoInformeBacheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        tipoInformeBacheo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoInformeBacheoActionPerformed(evt);
            }
        });
        jPanelBacheo.add(tipoInformeBacheo);
        tipoInformeBacheo.setBounds(580, 10, 180, 25);

        jLabel11.setText("Tramo Ejecutado");
        jPanelBacheo.add(jLabel11);
        jLabel11.setBounds(10, 50, 140, 50);

        jLabel12.setText("PR Inicio");
        jPanelBacheo.add(jLabel12);
        jLabel12.setBounds(160, 50, 60, 20);

        jLabel13.setText("PR Final");
        jPanelBacheo.add(jLabel13);
        jLabel13.setBounds(160, 80, 60, 20);

        listBacheoClima.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listBacheoClima);

        jPanelBacheo.add(jScrollPane1);
        jScrollPane1.setBounds(610, 50, 150, 60);

        jLabel14.setText("Clima");
        jPanelBacheo.add(jLabel14);
        jLabel14.setBounds(520, 50, 90, 50);

        jLabel15.setText("Horas trabajadas/hombre");
        jPanelBacheo.add(jLabel15);
        jLabel15.setBounds(10, 120, 220, 20);

        jLabel16.setText("Obreros por cuadrilla");
        jPanelBacheo.add(jLabel16);
        jLabel16.setBounds(10, 150, 220, 20);

        jLabel17.setText("Total horas utilizadas");
        jPanelBacheo.add(jLabel17);
        jLabel17.setBounds(10, 180, 220, 20);

        txtBacheoHorasUtilizadas.setEditable(false);
        jPanelBacheo.add(txtBacheoHorasUtilizadas);
        txtBacheoHorasUtilizadas.setBounds(230, 180, 100, 25);

        jLabel18.setText("Equipo");
        jPanelBacheo.add(jLabel18);
        jLabel18.setBounds(430, 120, 130, 20);
        jPanelBacheo.add(txtBacheoEquipo);
        txtBacheoEquipo.setBounds(560, 120, 200, 25);

        jLabel19.setText("Cantidad ejecutada");
        jPanelBacheo.add(jLabel19);
        jLabel19.setBounds(430, 150, 130, 20);

        txtBacheoCantidadEjecutada.setEditable(false);
        jPanelBacheo.add(txtBacheoCantidadEjecutada);
        txtBacheoCantidadEjecutada.setBounds(560, 150, 200, 25);

        btnBacheoContinuar.setText("Continuar");
        btnBacheoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacheoContinuarActionPerformed(evt);
            }
        });
        jPanelBacheo.add(btnBacheoContinuar);
        btnBacheoContinuar.setBounds(610, 300, 150, 25);

        btnBacheoGuardar.setText("Agregar nuevo");
        btnBacheoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacheoGuardarActionPerformed(evt);
            }
        });
        jPanelBacheo.add(btnBacheoGuardar);
        btnBacheoGuardar.setBounds(440, 300, 150, 25);

        jLabel25.setText("Rendimiento Esperado");
        jPanelBacheo.add(jLabel25);
        jLabel25.setBounds(430, 180, 130, 20);

        txtBacheoRendimiento.setEditable(false);
        jPanelBacheo.add(txtBacheoRendimiento);
        txtBacheoRendimiento.setBounds(560, 180, 200, 25);

        txtBacheoObservacion.setColumns(20);
        txtBacheoObservacion.setRows(1);
        jScrollPane2.setViewportView(txtBacheoObservacion);

        jPanelBacheo.add(jScrollPane2);
        jScrollPane2.setBounds(10, 230, 750, 61);

        jLabel26.setText("Observaciones");
        jPanelBacheo.add(jLabel26);
        jLabel26.setBounds(10, 210, 190, 14);

        txtBacheoHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtBacheoHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBacheoHorasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBacheoHorasFocusLost(evt);
            }
        });
        jPanelBacheo.add(txtBacheoHoras);
        txtBacheoHoras.setBounds(230, 120, 100, 25);

        try {
            txtBacheoPRFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelBacheo.add(txtBacheoPRFin);
        txtBacheoPRFin.setBounds(230, 80, 100, 25);

        try {
            txtBacheoPRInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelBacheo.add(txtBacheoPRInicio);
        txtBacheoPRInicio.setBounds(230, 50, 100, 25);

        txtBacheoObreros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtBacheoObreros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBacheoObrerosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBacheoObrerosFocusLost(evt);
            }
        });
        jPanelBacheo.add(txtBacheoObreros);
        txtBacheoObreros.setBounds(230, 150, 100, 25);

        jLabel38.setText("Indicadores agregados:");
        jPanelBacheo.add(jLabel38);
        jLabel38.setBounds(20, 310, 160, 14);
        jPanelBacheo.add(num_bacheos);
        num_bacheos.setBounds(20, 330, 90, 30);

        tabPanel.addTab("Bacheo", jPanelBacheo);

        jPanelParcheo.setLayout(null);

        tipoIndicadorParcheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parcheo" }));
        tipoIndicadorParcheo.setToolTipText("Seleccione un tipo de bacheo");
        tipoIndicadorParcheo.setEnabled(false);
        jPanelParcheo.add(tipoIndicadorParcheo);
        tipoIndicadorParcheo.setBounds(10, 10, 180, 25);

        tipoInformeParcheo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        jPanelParcheo.add(tipoInformeParcheo);
        tipoInformeParcheo.setBounds(580, 10, 180, 25);

        jLabel27.setText("Tramo Ejecutado");
        jPanelParcheo.add(jLabel27);
        jLabel27.setBounds(10, 50, 140, 50);

        jLabel28.setText("PR Inicio");
        jPanelParcheo.add(jLabel28);
        jLabel28.setBounds(160, 50, 60, 20);

        jLabel29.setText("PR Final");
        jPanelParcheo.add(jLabel29);
        jLabel29.setBounds(160, 80, 60, 20);

        listParcheoClima.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listParcheoClima);

        jPanelParcheo.add(jScrollPane3);
        jScrollPane3.setBounds(610, 50, 150, 60);

        jLabel30.setText("Clima");
        jPanelParcheo.add(jLabel30);
        jLabel30.setBounds(520, 50, 90, 50);

        jLabel31.setText("Horas trabajadas/hombre");
        jPanelParcheo.add(jLabel31);
        jLabel31.setBounds(10, 120, 220, 20);

        jLabel32.setText("Obreros por cuadrilla");
        jPanelParcheo.add(jLabel32);
        jLabel32.setBounds(10, 150, 220, 20);

        jLabel33.setText("Total horas utilizadas");
        jPanelParcheo.add(jLabel33);
        jLabel33.setBounds(10, 180, 220, 20);

        txtParcheoTotalHoras.setEditable(false);
        jPanelParcheo.add(txtParcheoTotalHoras);
        txtParcheoTotalHoras.setBounds(230, 180, 100, 25);

        jLabel34.setText("Equipo");
        jPanelParcheo.add(jLabel34);
        jLabel34.setBounds(430, 120, 130, 20);
        jPanelParcheo.add(txtEquipoParcheo);
        txtEquipoParcheo.setBounds(560, 120, 200, 25);

        jLabel35.setText("Cantidad ejecutada");
        jPanelParcheo.add(jLabel35);
        jLabel35.setBounds(430, 150, 130, 20);

        txtCantidadEjecutadaParcheo.setEditable(false);
        jPanelParcheo.add(txtCantidadEjecutadaParcheo);
        txtCantidadEjecutadaParcheo.setBounds(560, 150, 200, 25);

        btnParcheoContinuar.setText("Continuar");
        btnParcheoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcheoContinuarActionPerformed(evt);
            }
        });
        jPanelParcheo.add(btnParcheoContinuar);
        btnParcheoContinuar.setBounds(610, 300, 150, 25);

        btnParcheoGuardar.setText("Agregar nuevo");
        btnParcheoGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParcheoGuardarActionPerformed(evt);
            }
        });
        jPanelParcheo.add(btnParcheoGuardar);
        btnParcheoGuardar.setBounds(440, 300, 150, 25);

        jLabel36.setText("Rendimiento Esperado");
        jPanelParcheo.add(jLabel36);
        jLabel36.setBounds(430, 180, 130, 20);

        txtRendimientoParcheo.setEditable(false);
        jPanelParcheo.add(txtRendimientoParcheo);
        txtRendimientoParcheo.setBounds(560, 180, 200, 25);

        txtParcheoObservacion.setColumns(20);
        txtParcheoObservacion.setRows(1);
        jScrollPane4.setViewportView(txtParcheoObservacion);

        jPanelParcheo.add(jScrollPane4);
        jScrollPane4.setBounds(10, 230, 750, 61);

        jLabel37.setText("Observaciones");
        jPanelParcheo.add(jLabel37);
        jLabel37.setBounds(10, 210, 190, 14);

        txtParcheoHoras.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelParcheo.add(txtParcheoHoras);
        txtParcheoHoras.setBounds(230, 120, 100, 25);

        try {
            txtParcheoPRFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelParcheo.add(txtParcheoPRFin);
        txtParcheoPRFin.setBounds(230, 80, 100, 25);

        try {
            txtParcheoPRInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelParcheo.add(txtParcheoPRInicio);
        txtParcheoPRInicio.setBounds(230, 50, 100, 25);

        txtParcheoObreros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelParcheo.add(txtParcheoObreros);
        txtParcheoObreros.setBounds(230, 150, 100, 25);

        tabPanel.addTab("Parcheo", jPanelParcheo);

        jPanelLimpieza.setLayout(null);

        tipoLimpieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de limpieza", "Limpieza de bermas pavimentadas", "limpieza de bermas en afirmado", "limpíeza manual de cunetas en L y V", "limpieza de Zanjas de coronación revestidas y en tierra", "limpieza de encole y/o descole", "limpieza de obras", "limpieza de pequeñas obras hidraulicas (canales, camaras)", "limpieza manual del lecho del rio", "limpieza manual cursos de agua", "limpieza y pintura de barandas", "limpieza de calzada", "limpieza de señales y mojones", "limpieza de defensas metalicas" }));
        tipoLimpieza.setToolTipText("Seleccione un tipo de bacheo");
        jPanelLimpieza.add(tipoLimpieza);
        tipoLimpieza.setBounds(10, 10, 410, 25);

        tipoInformeLimpieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        jPanelLimpieza.add(tipoInformeLimpieza);
        tipoInformeLimpieza.setBounds(580, 10, 180, 25);

        jLabel93.setText("Tramo Ejecutado");
        jPanelLimpieza.add(jLabel93);
        jLabel93.setBounds(10, 50, 140, 50);

        jLabel94.setText("PR Inicio");
        jPanelLimpieza.add(jLabel94);
        jLabel94.setBounds(160, 50, 60, 20);

        jLabel95.setText("PR Final");
        jPanelLimpieza.add(jLabel95);
        jLabel95.setBounds(160, 80, 60, 20);

        listClimaLimpieza.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane15.setViewportView(listClimaLimpieza);

        jPanelLimpieza.add(jScrollPane15);
        jScrollPane15.setBounds(610, 50, 150, 60);

        jLabel96.setText("Clima");
        jPanelLimpieza.add(jLabel96);
        jLabel96.setBounds(520, 50, 90, 50);

        jLabel97.setText("Horas trabajadas/hombre");
        jPanelLimpieza.add(jLabel97);
        jLabel97.setBounds(10, 120, 220, 20);

        jLabel98.setText("Obreros por cuadrilla");
        jPanelLimpieza.add(jLabel98);
        jLabel98.setBounds(10, 150, 220, 20);

        jLabel99.setText("Total horas utilizadas");
        jPanelLimpieza.add(jLabel99);
        jLabel99.setBounds(10, 180, 220, 20);

        txtHorasUtilizadasLimpieza.setEditable(false);
        jPanelLimpieza.add(txtHorasUtilizadasLimpieza);
        txtHorasUtilizadasLimpieza.setBounds(230, 180, 100, 25);

        jLabel100.setText("Equipo");
        jPanelLimpieza.add(jLabel100);
        jLabel100.setBounds(430, 120, 130, 20);
        jPanelLimpieza.add(txtEquipoLimpieza);
        txtEquipoLimpieza.setBounds(560, 120, 200, 25);

        jLabel101.setText("Cantidad ejecutada");
        jPanelLimpieza.add(jLabel101);
        jLabel101.setBounds(430, 150, 130, 20);

        txtCantidadEjecutadaLimpieza.setEditable(false);
        jPanelLimpieza.add(txtCantidadEjecutadaLimpieza);
        txtCantidadEjecutadaLimpieza.setBounds(560, 150, 200, 25);

        btnContinuarLimpieza.setText("Continuar");
        btnContinuarLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarLimpiezaActionPerformed(evt);
            }
        });
        jPanelLimpieza.add(btnContinuarLimpieza);
        btnContinuarLimpieza.setBounds(610, 300, 150, 25);

        btnGuardarLimpieza.setText("Agregar nuevo");
        btnGuardarLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLimpiezaActionPerformed(evt);
            }
        });
        jPanelLimpieza.add(btnGuardarLimpieza);
        btnGuardarLimpieza.setBounds(440, 300, 150, 25);

        jLabel102.setText("Rendimiento Esperado");
        jPanelLimpieza.add(jLabel102);
        jLabel102.setBounds(430, 180, 130, 20);

        txtRendimientoLimpieza.setEditable(false);
        jPanelLimpieza.add(txtRendimientoLimpieza);
        txtRendimientoLimpieza.setBounds(560, 180, 200, 25);

        txtObservacionLimpieza.setColumns(20);
        txtObservacionLimpieza.setRows(1);
        jScrollPane16.setViewportView(txtObservacionLimpieza);

        jPanelLimpieza.add(jScrollPane16);
        jScrollPane16.setBounds(10, 230, 750, 61);

        jLabel103.setText("Observaciones");
        jPanelLimpieza.add(jLabel103);
        jLabel103.setBounds(10, 210, 190, 14);

        txtHorasLimpieza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelLimpieza.add(txtHorasLimpieza);
        txtHorasLimpieza.setBounds(230, 120, 100, 25);

        try {
            txtPRFinLimpieza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelLimpieza.add(txtPRFinLimpieza);
        txtPRFinLimpieza.setBounds(230, 80, 100, 25);

        try {
            txtPRInicioLimpieza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelLimpieza.add(txtPRInicioLimpieza);
        txtPRInicioLimpieza.setBounds(230, 50, 100, 25);

        txtObrerosLimpieza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelLimpieza.add(txtObrerosLimpieza);
        txtObrerosLimpieza.setBounds(230, 150, 100, 25);

        tabPanel.addTab("Limpieza", jPanelLimpieza);

        jPanelMantenimiento.setLayout(null);

        tipoMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de mantenimiento", "Mantenimiento rutinario puentes", "mantenimiento rutinario pontones" }));
        tipoMantenimiento.setToolTipText("Seleccione un tipo de bacheo");
        jPanelMantenimiento.add(tipoMantenimiento);
        tipoMantenimiento.setBounds(10, 10, 220, 25);

        tipoInformeMatenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        jPanelMantenimiento.add(tipoInformeMatenimiento);
        tipoInformeMatenimiento.setBounds(580, 10, 180, 25);

        jLabel104.setText("Tramo Ejecutado");
        jPanelMantenimiento.add(jLabel104);
        jLabel104.setBounds(10, 50, 140, 50);

        jLabel105.setText("PR Inicio");
        jPanelMantenimiento.add(jLabel105);
        jLabel105.setBounds(160, 50, 60, 20);

        jLabel106.setText("PR Final");
        jPanelMantenimiento.add(jLabel106);
        jLabel106.setBounds(160, 80, 60, 20);

        listClimaMantenimiento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane17.setViewportView(listClimaMantenimiento);

        jPanelMantenimiento.add(jScrollPane17);
        jScrollPane17.setBounds(610, 50, 150, 60);

        jLabel107.setText("Clima");
        jPanelMantenimiento.add(jLabel107);
        jLabel107.setBounds(520, 50, 90, 50);

        jLabel108.setText("Horas trabajadas/hombre");
        jPanelMantenimiento.add(jLabel108);
        jLabel108.setBounds(10, 120, 220, 20);

        jLabel109.setText("Obreros por cuadrilla");
        jPanelMantenimiento.add(jLabel109);
        jLabel109.setBounds(10, 150, 220, 20);

        jLabel110.setText("Total horas utilizadas");
        jPanelMantenimiento.add(jLabel110);
        jLabel110.setBounds(10, 180, 220, 20);

        txtHorasUtilizadasMantenimiento.setEditable(false);
        jPanelMantenimiento.add(txtHorasUtilizadasMantenimiento);
        txtHorasUtilizadasMantenimiento.setBounds(230, 180, 100, 25);

        jLabel111.setText("Equipo");
        jPanelMantenimiento.add(jLabel111);
        jLabel111.setBounds(430, 120, 130, 20);
        jPanelMantenimiento.add(txtEquipoManenimiento);
        txtEquipoManenimiento.setBounds(560, 120, 200, 25);

        jLabel112.setText("Cantidad ejecutada");
        jPanelMantenimiento.add(jLabel112);
        jLabel112.setBounds(430, 150, 130, 20);

        txtCantidadEjecutadaMantenimiento.setEditable(false);
        jPanelMantenimiento.add(txtCantidadEjecutadaMantenimiento);
        txtCantidadEjecutadaMantenimiento.setBounds(560, 150, 200, 25);

        btnContinuarMantenimiento.setText("Continuar");
        btnContinuarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarMantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnContinuarMantenimiento);
        btnContinuarMantenimiento.setBounds(610, 300, 150, 25);

        btnGuardarMantenimiento.setText("Agregar nuevo");
        btnGuardarMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMantenimientoActionPerformed(evt);
            }
        });
        jPanelMantenimiento.add(btnGuardarMantenimiento);
        btnGuardarMantenimiento.setBounds(440, 300, 150, 25);

        jLabel113.setText("Rendimiento Esperado");
        jPanelMantenimiento.add(jLabel113);
        jLabel113.setBounds(430, 180, 130, 20);

        txtRendimientoMantenimiento.setEditable(false);
        jPanelMantenimiento.add(txtRendimientoMantenimiento);
        txtRendimientoMantenimiento.setBounds(560, 180, 200, 25);

        txtObservacionMantenimiento.setColumns(20);
        txtObservacionMantenimiento.setRows(1);
        jScrollPane18.setViewportView(txtObservacionMantenimiento);

        jPanelMantenimiento.add(jScrollPane18);
        jScrollPane18.setBounds(10, 230, 750, 61);

        jLabel114.setText("Observaciones");
        jPanelMantenimiento.add(jLabel114);
        jLabel114.setBounds(10, 210, 200, 14);

        txtHorasMantenimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelMantenimiento.add(txtHorasMantenimiento);
        txtHorasMantenimiento.setBounds(230, 120, 100, 25);

        try {
            txtPRFinMantenimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelMantenimiento.add(txtPRFinMantenimiento);
        txtPRFinMantenimiento.setBounds(230, 80, 100, 25);

        try {
            txtPRInicioMantenimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelMantenimiento.add(txtPRInicioMantenimiento);
        txtPRInicioMantenimiento.setBounds(230, 50, 100, 25);

        txtObrerosMantenimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelMantenimiento.add(txtObrerosMantenimiento);
        txtObrerosMantenimiento.setBounds(230, 150, 100, 25);

        tabPanel.addTab("Mantenimiento", jPanelMantenimiento);

        jPanelObrasComplementarias.setLayout(null);

        tipoObraComplementaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de obras complementarias", "Despeje de derrumbes", "Roceria y desmonte manual", "Poda", "corte y/o retiro de arboles", "Reposición de la lamina de las señales (no inlcuye suministro)", "Reposición del poste de la señal (no incluye suministro)", "Reposición de la señal completa (no incluye suministro)", "Reposición de mojones de referencia", "Arreglo de señales y despeje", "Vigilancia", "Emergencias", "Erradicación de basureros", "Retiro de avisos", "" }));
        tipoObraComplementaria.setToolTipText("Seleccione un tipo de bacheo");
        jPanelObrasComplementarias.add(tipoObraComplementaria);
        tipoObraComplementaria.setBounds(10, 10, 400, 25);

        tipoInformeObraComplementaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        jPanelObrasComplementarias.add(tipoInformeObraComplementaria);
        tipoInformeObraComplementaria.setBounds(580, 10, 180, 25);

        jLabel115.setText("Tramo Ejecutado");
        jPanelObrasComplementarias.add(jLabel115);
        jLabel115.setBounds(10, 50, 140, 50);

        jLabel116.setText("PR Inicio");
        jPanelObrasComplementarias.add(jLabel116);
        jLabel116.setBounds(160, 50, 60, 20);

        jLabel117.setText("PR Final");
        jPanelObrasComplementarias.add(jLabel117);
        jLabel117.setBounds(160, 80, 60, 20);

        listClimaObraComplementaria.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane19.setViewportView(listClimaObraComplementaria);

        jPanelObrasComplementarias.add(jScrollPane19);
        jScrollPane19.setBounds(610, 50, 150, 60);

        jLabel118.setText("Clima");
        jPanelObrasComplementarias.add(jLabel118);
        jLabel118.setBounds(520, 50, 90, 50);

        jLabel119.setText("Horas trabajadas/hombre");
        jPanelObrasComplementarias.add(jLabel119);
        jLabel119.setBounds(10, 120, 220, 20);

        jLabel120.setText("Obreros por cuadrilla");
        jPanelObrasComplementarias.add(jLabel120);
        jLabel120.setBounds(10, 150, 220, 20);

        jLabel121.setText("Total horas utilizadas");
        jPanelObrasComplementarias.add(jLabel121);
        jLabel121.setBounds(10, 180, 220, 20);

        txtHorasUtilizadasObraComplementaria.setEditable(false);
        jPanelObrasComplementarias.add(txtHorasUtilizadasObraComplementaria);
        txtHorasUtilizadasObraComplementaria.setBounds(230, 180, 100, 25);

        jLabel122.setText("Equipo");
        jPanelObrasComplementarias.add(jLabel122);
        jLabel122.setBounds(430, 120, 130, 20);
        jPanelObrasComplementarias.add(txtEquipoObraComplementaria);
        txtEquipoObraComplementaria.setBounds(560, 120, 200, 25);

        jLabel123.setText("Cantidad ejecutada");
        jPanelObrasComplementarias.add(jLabel123);
        jLabel123.setBounds(430, 150, 130, 20);

        txtCantidadEjecutadaObraComplementaria.setEditable(false);
        jPanelObrasComplementarias.add(txtCantidadEjecutadaObraComplementaria);
        txtCantidadEjecutadaObraComplementaria.setBounds(560, 150, 200, 25);

        btnContinuarObraComplementaria.setText("Continuar");
        btnContinuarObraComplementaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarObraComplementariaActionPerformed(evt);
            }
        });
        jPanelObrasComplementarias.add(btnContinuarObraComplementaria);
        btnContinuarObraComplementaria.setBounds(610, 300, 150, 25);

        btnGuardarObraComplementaria.setText("Agregar nuevo");
        btnGuardarObraComplementaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarObraComplementariaActionPerformed(evt);
            }
        });
        jPanelObrasComplementarias.add(btnGuardarObraComplementaria);
        btnGuardarObraComplementaria.setBounds(440, 300, 150, 25);

        jLabel124.setText("Rendimiento Esperado");
        jPanelObrasComplementarias.add(jLabel124);
        jLabel124.setBounds(430, 180, 130, 20);

        txtRendimientoObraComplementaria.setEditable(false);
        jPanelObrasComplementarias.add(txtRendimientoObraComplementaria);
        txtRendimientoObraComplementaria.setBounds(560, 180, 200, 25);

        txtObservacionObraComplementaria.setColumns(20);
        txtObservacionObraComplementaria.setRows(1);
        jScrollPane20.setViewportView(txtObservacionObraComplementaria);

        jPanelObrasComplementarias.add(jScrollPane20);
        jScrollPane20.setBounds(10, 230, 750, 61);

        jLabel125.setText("Observaciones");
        jPanelObrasComplementarias.add(jLabel125);
        jLabel125.setBounds(10, 210, 220, 14);

        txtHorasObraComplementaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelObrasComplementarias.add(txtHorasObraComplementaria);
        txtHorasObraComplementaria.setBounds(230, 120, 100, 25);

        try {
            txtPRFinObraComplementaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelObrasComplementarias.add(txtPRFinObraComplementaria);
        txtPRFinObraComplementaria.setBounds(230, 80, 100, 25);

        try {
            txtPRInicioObraComplementaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelObrasComplementarias.add(txtPRInicioObraComplementaria);
        txtPRInicioObraComplementaria.setBounds(230, 50, 100, 25);

        txtObrerosObraComplementaria.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelObrasComplementarias.add(txtObrerosObraComplementaria);
        txtObrerosObraComplementaria.setBounds(230, 150, 100, 25);

        tabPanel.addTab("Obras Complementarias", jPanelObrasComplementarias);

        jPanelPinturas.setLayout(null);

        tipoPintura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de pintura", "Renovacion de las indicaciones en el mojon", "Pintura de cabezotes", "Pintura de muros", "Pintura de resaltos", "Pintura de bordillos", "Pintura de referenciación de la calzada", "Pintura de marcas viales" }));
        tipoPintura.setToolTipText("Seleccione un tipo de bacheo");
        jPanelPinturas.add(tipoPintura);
        tipoPintura.setBounds(10, 10, 320, 25);

        tipoInformePintura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Informe", "Diario", "Semanal", "Mensual" }));
        jPanelPinturas.add(tipoInformePintura);
        tipoInformePintura.setBounds(580, 10, 180, 25);

        jLabel126.setText("Tramo Ejecutado");
        jPanelPinturas.add(jLabel126);
        jLabel126.setBounds(10, 50, 140, 50);

        jLabel127.setText("PR Inicio");
        jPanelPinturas.add(jLabel127);
        jLabel127.setBounds(160, 50, 60, 20);

        jLabel128.setText("PR Final");
        jPanelPinturas.add(jLabel128);
        jLabel128.setBounds(160, 80, 60, 20);

        listClimaPintura.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Seco", "Soleado", "Lluvioso", "Humedo", "Nublado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane21.setViewportView(listClimaPintura);

        jPanelPinturas.add(jScrollPane21);
        jScrollPane21.setBounds(610, 50, 150, 60);

        jLabel129.setText("Clima");
        jPanelPinturas.add(jLabel129);
        jLabel129.setBounds(520, 50, 90, 50);

        jLabel130.setText("Horas trabajadas/hombre");
        jPanelPinturas.add(jLabel130);
        jLabel130.setBounds(10, 120, 220, 20);

        jLabel131.setText("Obreros por cuadrilla");
        jPanelPinturas.add(jLabel131);
        jLabel131.setBounds(10, 150, 220, 20);

        jLabel132.setText("Total horas utilizadas");
        jPanelPinturas.add(jLabel132);
        jLabel132.setBounds(10, 180, 220, 20);

        txtHorasUtilizadasPintura.setEditable(false);
        jPanelPinturas.add(txtHorasUtilizadasPintura);
        txtHorasUtilizadasPintura.setBounds(230, 180, 100, 25);

        jLabel133.setText("Equipo");
        jPanelPinturas.add(jLabel133);
        jLabel133.setBounds(430, 120, 130, 20);
        jPanelPinturas.add(txtEquipoPintura);
        txtEquipoPintura.setBounds(560, 120, 200, 25);

        jLabel134.setText("Cantidad ejecutada");
        jPanelPinturas.add(jLabel134);
        jLabel134.setBounds(430, 150, 130, 20);

        txtCantidadEjecutadaPintura.setEditable(false);
        jPanelPinturas.add(txtCantidadEjecutadaPintura);
        txtCantidadEjecutadaPintura.setBounds(560, 150, 200, 25);

        btnGuardarPintura.setText("Agregar nuevo");
        btnGuardarPintura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPinturaActionPerformed(evt);
            }
        });
        jPanelPinturas.add(btnGuardarPintura);
        btnGuardarPintura.setBounds(610, 300, 150, 25);

        jLabel135.setText("Rendimiento Esperado");
        jPanelPinturas.add(jLabel135);
        jLabel135.setBounds(430, 180, 130, 20);

        txtRendimientoPintura.setEditable(false);
        jPanelPinturas.add(txtRendimientoPintura);
        txtRendimientoPintura.setBounds(560, 180, 200, 25);

        txtObservacionPintura.setColumns(20);
        txtObservacionPintura.setRows(1);
        jScrollPane22.setViewportView(txtObservacionPintura);

        jPanelPinturas.add(jScrollPane22);
        jScrollPane22.setBounds(10, 230, 750, 61);

        jLabel136.setText("Observaciones");
        jPanelPinturas.add(jLabel136);
        jLabel136.setBounds(10, 210, 220, 14);

        txtHorasPintura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelPinturas.add(txtHorasPintura);
        txtHorasPintura.setBounds(230, 120, 100, 25);

        try {
            txtPRFinPintura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelPinturas.add(txtPRFinPintura);
        txtPRFinPintura.setBounds(230, 80, 100, 25);

        try {
            txtPRInicioPintura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###+###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanelPinturas.add(txtPRInicioPintura);
        txtPRInicioPintura.setBounds(230, 50, 100, 25);

        txtObrerosPintura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelPinturas.add(txtObrerosPintura);
        txtObrerosPintura.setBounds(230, 150, 100, 25);

        tabPanel.addTab("Pinturas", jPanelPinturas);

        add(tabPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIngenieroResidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIngenieroResidenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIngenieroResidenteActionPerformed

    private void txtSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSectorActionPerformed

    private void btnGeneralidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralidadesActionPerformed
        tabPanel.setSelectedComponent(jPanelBacheo);
    }//GEN-LAST:event_btnGeneralidadesActionPerformed

    private void btnBacheoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacheoContinuarActionPerformed
        tabPanel.setSelectedComponent(jPanelParcheo);
    }//GEN-LAST:event_btnBacheoContinuarActionPerformed

    private void btnBacheoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacheoGuardarActionPerformed
        getBacheo();
    }//GEN-LAST:event_btnBacheoGuardarActionPerformed

    private void btnParcheoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcheoContinuarActionPerformed
        tabPanel.setSelectedComponent(jPanelLimpieza);
    }//GEN-LAST:event_btnParcheoContinuarActionPerformed

    private void btnParcheoGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParcheoGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnParcheoGuardarActionPerformed

    private void btnContinuarLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarLimpiezaActionPerformed
        tabPanel.setSelectedComponent(jPanelMantenimiento);
    }//GEN-LAST:event_btnContinuarLimpiezaActionPerformed

    private void btnGuardarLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLimpiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarLimpiezaActionPerformed

    private void btnContinuarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarMantenimientoActionPerformed
        tabPanel.setSelectedComponent(jPanelObrasComplementarias);
    }//GEN-LAST:event_btnContinuarMantenimientoActionPerformed

    private void btnGuardarMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMantenimientoActionPerformed

    private void btnContinuarObraComplementariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarObraComplementariaActionPerformed
        tabPanel.setSelectedComponent(jPanelPinturas);
    }//GEN-LAST:event_btnContinuarObraComplementariaActionPerformed

    private void btnGuardarObraComplementariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarObraComplementariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarObraComplementariaActionPerformed

    private void btnGuardarPinturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPinturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPinturaActionPerformed

    private void txtBacheoObrerosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacheoObrerosFocusLost
        calcularHorasUtilizadasBacheo();
    }//GEN-LAST:event_txtBacheoObrerosFocusLost

    private void txtBacheoHorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacheoHorasFocusLost
        calcularHorasUtilizadasBacheo();
    }//GEN-LAST:event_txtBacheoHorasFocusLost

    private void tipoInformeBacheoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoInformeBacheoActionPerformed
        calcularHorasUtilizadasBacheo();
    }//GEN-LAST:event_tipoInformeBacheoActionPerformed

    private void txtBacheoHorasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacheoHorasFocusGained
        calcularHorasUtilizadasBacheo();
    }//GEN-LAST:event_txtBacheoHorasFocusGained

    private void txtBacheoObrerosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBacheoObrerosFocusGained
        calcularHorasUtilizadasBacheo();
    }//GEN-LAST:event_txtBacheoObrerosFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacheoContinuar;
    private javax.swing.JButton btnBacheoGuardar;
    private javax.swing.JButton btnContinuarLimpieza;
    private javax.swing.JButton btnContinuarMantenimiento;
    private javax.swing.JButton btnContinuarObraComplementaria;
    private javax.swing.JButton btnGeneralidades;
    private javax.swing.JButton btnGuardarLimpieza;
    private javax.swing.JButton btnGuardarMantenimiento;
    private javax.swing.JButton btnGuardarObraComplementaria;
    private javax.swing.JButton btnGuardarPintura;
    private javax.swing.JButton btnParcheoContinuar;
    private javax.swing.JButton btnParcheoGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanelBacheo;
    private javax.swing.JPanel jPanelGeneralidades;
    private javax.swing.JPanel jPanelLimpieza;
    private javax.swing.JPanel jPanelMantenimiento;
    private javax.swing.JPanel jPanelObrasComplementarias;
    private javax.swing.JPanel jPanelParcheo;
    private javax.swing.JPanel jPanelPinturas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> listBacheoClima;
    private javax.swing.JList<String> listClimaLimpieza;
    private javax.swing.JList<String> listClimaMantenimiento;
    private javax.swing.JList<String> listClimaObraComplementaria;
    private javax.swing.JList<String> listClimaPintura;
    private javax.swing.JList<String> listParcheoClima;
    private javax.swing.JLabel num_bacheos;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JComboBox<String> tipoIndicadorBacheo;
    private javax.swing.JComboBox<String> tipoIndicadorParcheo;
    private javax.swing.JComboBox<String> tipoInformeBacheo;
    private javax.swing.JComboBox<String> tipoInformeLimpieza;
    private javax.swing.JComboBox<String> tipoInformeMatenimiento;
    private javax.swing.JComboBox<String> tipoInformeObraComplementaria;
    private javax.swing.JComboBox<String> tipoInformeParcheo;
    private javax.swing.JComboBox<String> tipoInformePintura;
    private javax.swing.JComboBox<String> tipoLimpieza;
    private javax.swing.JComboBox<String> tipoMantenimiento;
    private javax.swing.JComboBox<String> tipoObraComplementaria;
    private javax.swing.JComboBox<String> tipoPintura;
    private javax.swing.JTextField txtAMV;
    private javax.swing.JTextField txtBacheoCantidadEjecutada;
    private javax.swing.JTextField txtBacheoEquipo;
    private javax.swing.JFormattedTextField txtBacheoHoras;
    private javax.swing.JTextField txtBacheoHorasUtilizadas;
    private javax.swing.JFormattedTextField txtBacheoObreros;
    private javax.swing.JTextArea txtBacheoObservacion;
    private javax.swing.JFormattedTextField txtBacheoPRFin;
    private javax.swing.JFormattedTextField txtBacheoPRInicio;
    private javax.swing.JTextField txtBacheoRendimiento;
    private javax.swing.JTextField txtCTA;
    private javax.swing.JTextField txtCantidadEjecutadaLimpieza;
    private javax.swing.JTextField txtCantidadEjecutadaMantenimiento;
    private javax.swing.JTextField txtCantidadEjecutadaObraComplementaria;
    private javax.swing.JTextField txtCantidadEjecutadaParcheo;
    private javax.swing.JTextField txtCantidadEjecutadaPintura;
    private javax.swing.JFormattedTextField txtCelulares;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccionOficina;
    private javax.swing.JTextField txtEquipoLimpieza;
    private javax.swing.JTextField txtEquipoManenimiento;
    private javax.swing.JTextField txtEquipoObraComplementaria;
    private javax.swing.JTextField txtEquipoParcheo;
    private javax.swing.JTextField txtEquipoPintura;
    private javax.swing.JTextField txtFax;
    private javax.swing.JFormattedTextField txtHorasLimpieza;
    private javax.swing.JFormattedTextField txtHorasMantenimiento;
    private javax.swing.JFormattedTextField txtHorasObraComplementaria;
    private javax.swing.JFormattedTextField txtHorasPintura;
    private javax.swing.JTextField txtHorasUtilizadasLimpieza;
    private javax.swing.JTextField txtHorasUtilizadasMantenimiento;
    private javax.swing.JTextField txtHorasUtilizadasObraComplementaria;
    private javax.swing.JTextField txtHorasUtilizadasPintura;
    private javax.swing.JTextField txtIngenieroAuxiliar;
    private javax.swing.JTextField txtIngenieroResidente;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JFormattedTextField txtObrerosLimpieza;
    private javax.swing.JFormattedTextField txtObrerosMantenimiento;
    private javax.swing.JFormattedTextField txtObrerosObraComplementaria;
    private javax.swing.JFormattedTextField txtObrerosPintura;
    private javax.swing.JTextArea txtObservacionLimpieza;
    private javax.swing.JTextArea txtObservacionMantenimiento;
    private javax.swing.JTextArea txtObservacionObraComplementaria;
    private javax.swing.JTextArea txtObservacionPintura;
    private javax.swing.JFormattedTextField txtPRFinLimpieza;
    private javax.swing.JFormattedTextField txtPRFinMantenimiento;
    private javax.swing.JFormattedTextField txtPRFinObraComplementaria;
    private javax.swing.JFormattedTextField txtPRFinPintura;
    private javax.swing.JFormattedTextField txtPRFinalGeneralidades;
    private javax.swing.JFormattedTextField txtPRInicialGeneralidades1;
    private javax.swing.JFormattedTextField txtPRInicioLimpieza;
    private javax.swing.JFormattedTextField txtPRInicioMantenimiento;
    private javax.swing.JFormattedTextField txtPRInicioObraComplementaria;
    private javax.swing.JFormattedTextField txtPRInicioPintura;
    private javax.swing.JFormattedTextField txtParcheoHoras;
    private javax.swing.JFormattedTextField txtParcheoObreros;
    private javax.swing.JTextArea txtParcheoObservacion;
    private javax.swing.JFormattedTextField txtParcheoPRFin;
    private javax.swing.JFormattedTextField txtParcheoPRInicio;
    private javax.swing.JTextField txtParcheoTotalHoras;
    private javax.swing.JTextField txtRendimientoLimpieza;
    private javax.swing.JTextField txtRendimientoMantenimiento;
    private javax.swing.JTextField txtRendimientoObraComplementaria;
    private javax.swing.JTextField txtRendimientoParcheo;
    private javax.swing.JTextField txtRendimientoPintura;
    private javax.swing.JTextField txtSector;
    private javax.swing.JTextField txtSectorAdministrativo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoTerreno;
    // End of variables declaration//GEN-END:variables

    public ProyectoDto getProyecto() {
        ProyectoDto proyectoDto = new ProyectoDto();
        proyectoDto.setProyecto(getGeneralidades());
        try {
            getBacheo();
            getParcheo();
            getLimpieza();
            getMantenimiento();
            getObras();
            getPintura();
        } catch (Exception e) {
            e.printStackTrace();
        }
        proyectoDto.setIndicadores(indicadors);
        return proyectoDto;
    }

    private Proyecto getGeneralidades() {
        Proyecto pr = new Proyecto();
        pr.setAmv(txtAMV.getText());
        pr.setCelular(txtCelulares.getText());
        pr.setCorreo(txtCorreo.getText());
        pr.setCta(txtCTA.getText());
        pr.setDireccionOficina(txtDireccionOficina.getText());
        pr.setFax(txtFax.getText());
        pr.setIngenieroAuxiliar(txtIngenieroAuxiliar.getText());
        pr.setIngenieroResidente(txtIngenieroResidente.getText());
        pr.setLongitud(txtLongitud.getText());
        pr.setPrFinal(txtPRFinalGeneralidades.getText());
        pr.setPrInicial(txtPRFinalGeneralidades.getText());
        pr.setSector(txtSector.getText());
        pr.setSectorAdministrativo(txtSectorAdministrativo.getText());
        pr.setTelefono(txtTelefono.getText());
        pr.setTipoTerreno(txtTipoTerreno.getText());
        return pr;
    }

    private void getBacheo() {
        if (tipoIndicadorBacheo.getSelectedIndex() == 0) {
            System.out.println("Sin bacheo");
            return;
        }
        if (num_bacheos.getText().isEmpty()) {
            num_bacheos.setText("1");
        } else {
            int bacheos = Integer.parseInt(num_bacheos.getText()) + 1;
            num_bacheos.setText("" + bacheos);
        }

        Indicador indicador = new Indicador();
        indicador.setClimas(listBacheoClima.getSelectedValuesList());
        indicador.setEquipo(txtBacheoEquipo.getText());
        indicador.setObservacion(txtBacheoObservacion.getText());
        indicador.setPrFin(txtBacheoPRFin.getText());
        indicador.setPrInicio(txtBacheoPRInicio.getText());
        indicador.setRendimiento(txtBacheoRendimiento.getText());
        indicador.setTipoIndicador(tipoIndicadorBacheo.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformeBacheo.getSelectedItem().toString());
        indicador.setTotalHoras(txtBacheoHorasUtilizadas.getText());
        if (!txtBacheoCantidadEjecutada.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtBacheoCantidadEjecutada.getText()));
        }
        if (!txtBacheoHoras.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtBacheoHoras.getText()));
        }
        if (!txtBacheoObreros.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtBacheoObreros.getText()));
        }
        indicadors.add(indicador);
    }

    private void getParcheo() {
        Indicador indicador = new Indicador();
        indicador.setClimas(listParcheoClima.getSelectedValuesList());
        indicador.setEquipo(txtEquipoParcheo.getText());
        indicador.setObservacion(txtParcheoObservacion.getText());
        indicador.setPrFin(txtParcheoPRFin.getText());
        indicador.setPrInicio(txtParcheoPRInicio.getText());
        indicador.setRendimiento(txtRendimientoParcheo.getText());
        indicador.setTipoIndicador(tipoIndicadorParcheo.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformeParcheo.getSelectedItem().toString());
        indicador.setTotalHoras(txtParcheoTotalHoras.getText());
        if (!txtCantidadEjecutadaParcheo.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtCantidadEjecutadaParcheo.getText()));
        }
        if (!txtParcheoHoras.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtParcheoHoras.getText()));
        }
        if (!txtParcheoObreros.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtParcheoObreros.getText()));
        }
        indicadors.add(indicador);
    }

    private void getLimpieza() {
        if (tipoLimpieza.getSelectedIndex() == 0) {
            System.out.println("Sin limpieza");
            return;
        }
        Indicador indicador = new Indicador();
        indicador.setClimas(listClimaLimpieza.getSelectedValuesList());
        indicador.setEquipo(txtEquipoLimpieza.getText());
        indicador.setObservacion(txtObservacionLimpieza.getText());
        indicador.setPrFin(txtPRFinLimpieza.getText());
        indicador.setPrInicio(txtPRInicioLimpieza.getText());
        indicador.setRendimiento(txtRendimientoLimpieza.getText());
        indicador.setTipoIndicador(tipoLimpieza.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformeLimpieza.getSelectedItem().toString());
        indicador.setTotalHoras(txtHorasUtilizadasLimpieza.getText());
        if (!txtCantidadEjecutadaLimpieza.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtCantidadEjecutadaLimpieza.getText()));
        }
        if (!txtHorasLimpieza.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtHorasLimpieza.getText()));
        }
        if (!txtObrerosLimpieza.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtObrerosLimpieza.getText()));
        }
        indicadors.add(indicador);
    }

    private void getMantenimiento() {
        if (tipoMantenimiento.getSelectedIndex() == 0) {
            System.out.println("Sin mantenimiento");
            return;
        }
        Indicador indicador = new Indicador();
        indicador.setClimas(listClimaMantenimiento.getSelectedValuesList());
        indicador.setEquipo(txtEquipoManenimiento.getText());
        indicador.setObservacion(txtObservacionMantenimiento.getText());
        indicador.setPrFin(txtPRFinMantenimiento.getText());
        indicador.setPrInicio(txtPRInicioMantenimiento.getText());
        indicador.setRendimiento(txtRendimientoMantenimiento.getText());
        indicador.setTipoIndicador(tipoMantenimiento.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformeMatenimiento.getSelectedItem().toString());
        indicador.setTotalHoras(txtHorasUtilizadasMantenimiento.getText());
        if (!txtCantidadEjecutadaMantenimiento.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtCantidadEjecutadaMantenimiento.getText()));
        }
        if (!txtHorasMantenimiento.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtHorasMantenimiento.getText()));
        }
        if (!txtObrerosMantenimiento.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtObrerosMantenimiento.getText()));
        }
        indicadors.add(indicador);
    }

    private void getObras() {
        if (tipoObraComplementaria.getSelectedIndex() == 0) {
            System.out.println("Sin obras");
            return;
        }
        Indicador indicador = new Indicador();
        indicador.setClimas(listClimaObraComplementaria.getSelectedValuesList());
        indicador.setEquipo(txtEquipoObraComplementaria.getText());
        indicador.setObservacion(txtObservacionObraComplementaria.getText());
        indicador.setPrFin(txtPRFinObraComplementaria.getText());
        indicador.setPrInicio(txtPRInicioObraComplementaria.getText());
        indicador.setRendimiento(txtRendimientoObraComplementaria.getText());
        indicador.setTipoIndicador(tipoObraComplementaria.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformeObraComplementaria.getSelectedItem().toString());
        indicador.setTotalHoras(txtHorasUtilizadasObraComplementaria.getText());
        if (!txtCantidadEjecutadaObraComplementaria.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtCantidadEjecutadaObraComplementaria.getText()));
        }
        if (!txtHorasObraComplementaria.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtHorasObraComplementaria.getText()));
        }
        if (!txtObrerosObraComplementaria.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtObrerosObraComplementaria.getText()));
        }
        indicadors.add(indicador);
    }

    private void getPintura() {
        if (tipoPintura.getSelectedIndex() == 0) {
            System.out.println("Sin pintura");
            return;
        }
        Indicador indicador = new Indicador();
        indicador.setClimas(listClimaPintura.getSelectedValuesList());
        indicador.setEquipo(txtEquipoPintura.getText());
        indicador.setObservacion(txtObservacionPintura.getText());
        indicador.setPrFin(txtPRFinPintura.getText());
        indicador.setPrInicio(txtPRInicioPintura.getText());
        indicador.setRendimiento(txtRendimientoPintura.getText());
        indicador.setTipoIndicador(tipoPintura.getSelectedItem().toString());
        indicador.setTipoInforme(tipoInformePintura.getSelectedItem().toString());
        indicador.setTotalHoras(txtHorasUtilizadasPintura.getText());
        if (!txtCantidadEjecutadaPintura.getText().isEmpty()) {
            indicador.setCantidadEjecutada(Integer.parseInt(txtCantidadEjecutadaPintura.getText()));
        }
        if (!txtHorasPintura.getText().isEmpty()) {
            indicador.setHorasTrabajadas(Integer.parseInt(txtHorasPintura.getText()));
        }
        if (!txtObrerosPintura.getText().isEmpty()) {
            indicador.setObreros(Integer.parseInt(txtObrerosPintura.getText()));
        }
        indicadors.add(indicador);
    }

    private void calcularHorasUtilizadasBacheo() {
        int obreros = 0;
        int horas = 0;
        if (Objects.nonNull(txtBacheoObreros.getValue())) {
            obreros = Integer.parseInt(txtBacheoObreros.getValue().toString());
        }
        if (Objects.nonNull(txtBacheoHoras.getValue())) {
            horas = Integer.parseInt(txtBacheoHoras.getValue().toString());
        }
        int total = obreros * horas;
        if (tipoInformeBacheo.getSelectedIndex() != 0 && total > 0) {
            txtBacheoHorasUtilizadas.setText(total + " " + tipoInformeBacheo.getSelectedItem().toString());
        }
    }
}
